### ISSUE TITLE
Löschen eines Buches führt zu Error, funktioniert aber

### ISSUE THREAD

**Issue by fb4thxUall** [jzakotnik/openlibry#118]
Das Löschen eines Buches führt zu folgendem Fehler im Log, funktioniert aber trotzdem und ist nicht dringend:

API resolved without sending a response for /api/images/2?1, this may result in stalled requests.
 GET /api/images/2?1 200 in 477ms
 ✓ Compiled /api/book/[id] in 396ms (543 modules)
 DELETE /api/book/2 200 in 453ms
 GET /_next/data/development/book.json 200 in 100ms
 GET /_next/data/development/book/3.json?bookid=3 200 in 115ms
Error: ENOENT: no such file or directory, open '/app/public/coverimages/default.jpg'
    at Object.openSync (node:fs:582:18)
    at Object.readFileSync (node:fs:461:35)
    at handle (webpack-internal:///(api)/./pages/api/images/[id].ts:46:83)
    at K (/home/big/openlibry/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2877)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async U.render (/home/big/openlibry/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3955)
    at async DevServer.runApi (/home/big/openlibry/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/home/big/openlibry/node_modules/next/dist/server/next-server.js:269:37)
    at async DevServer.handleRequestImpl (/home/big/openlibry/node_modules/next/dist/server/base-server.js:816:17)
    at async /home/big/openlibry/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/home/big/openlibry/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/home/big/openlibry/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/home/big/openlibry/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/home/big/openlibry/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/home/big/openlibry/node_modules/next/dist/server/lib/router-server.js:377:13) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/public/coverimages/default.jpg'
}

**Comment by jzakotnik** [comment]
Das schaffe ich nicht zu reproduzieren - scheinbar versucht er ein Bild zu laden, was es nicht gibt und lädt dann das default Bild (zwischen book ID 2 oder 3). Hatte das gelöchte Buch ein Bild?

**Comment by fb4thxUall** [comment]
Nope, hatte keins. Hat auch definitiv keine Prio mMn

Am 21. Juli 2024 10:02:40 MESZ schrieb Jure Zakotnik ***@***.***>:
>Das schaffe ich nicht zu reproduzieren - scheinbar versucht er ein Bild zu laden, was es nicht gibt und lädt dann das default Bild (zwischen book ID 2 oder 3). Hatte das gelöchte Buch ein Bild?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jzakotnik/openlibry/issues/118#issuecomment-2241518073
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by fb4thxUall** [comment]
Problem tritt in der aktuellen Version nicht mehr auf.
